### ISSUE TITLE
Build Error : Headline1, Headline2 ... etc not defined.

### ISSUE THREAD

**Issue by blinkinfo** [ashishkhuraishy/CovidUpdates#10]
in ThemeData headline1, headline2 upto 5 or 6 maybe.. and subtitle1, subtitle2 not defined.
Build error

![Screenshot (92)](https://user-images.githubusercontent.com/53660007/78459181-3f1fd480-7685-11ea-93c6-e49fd3317557.png)

**Comment by ashishkhuraishy** [comment]
Thanks for pointing that out :)
