### ISSUE TITLE
🐞: APK installation error on AVD

### ISSUE THREAD

**Issue by nandgator** [ashishkhuraishy/CovidUpdates#8]
## Bug
[CovidUpdates](https://github.com/ashishkhuraishy/CovidUpdates/raw/master/output/Covid%20Updates.apk) apk installation fails with error on AVD with API v29 (android 10-Q).

## Screenshot
![Screenshot from 2020-03-27 11-46-02](https://user-images.githubusercontent.com/38415384/77728126-db146500-7021-11ea-8977-cce0394738fe.png)

**Comment by ashishkhuraishy** [comment]
hey sorry for late reply, is this happening while you run the code or when you tried to install with the apk from the link?

**Comment by nandgator** [comment]
> hey sorry for late reply

It's okay man...

> Is this happening while you run the code or when you tried to install with the apk from the link?

When I tired to install the APK from the link (if you have not updated it yet: https://github.com/ashishkhuraishy/CovidUpdates/raw/master/output/Covid%20Updates.apk).

**Comment by ashishkhuraishy** [comment]
Hey i've updated the download link can you please check the new one and report back😄

**Comment by nandgator** [comment]
Hey bro, I'm getting the same error. But I've got something interesting...

> First when I downloaded the (updated) APK, It's giving me this:
![Screenshot from 2020-04-07 14-17-04](https://user-images.githubusercontent.com/38415384/78650060-03327c80-78dc-11ea-904d-d7347098b096.png)

>I tried changing the permissions, but in vain:
![Screenshot from 2020-04-07 14-19-47](https://user-images.githubusercontent.com/38415384/78650481-9966a280-78dc-11ea-95ef-3d874cd13a12.png)

Finally I did something sensible... 😅... I tried to install the apk with `adb` and it gave me this error:
```java
joe  (e) base  ~  Downloads  adb install covid.apk 
Performing Streamed Install
adb: failed to install covid.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```
So, right over to stackexchange...
- I think this can be your problem: https://stackoverflow.com/questions/24572052, https://android.stackexchange.com/questions/172932, https://askubuntu.com/questions/903995
- And this can be a solution: https://stackoverflow.com/questions/36414219

By the way my emulator has x86 architecture. 
Tell me if it helps.

**Comment by nandgator** [comment]
Hey bro, sorry to bother. As this issue https://github.com/flutter/flutter/issues/58393 says, `x86` architecture is not supported.

**Comment by ashishkhuraishy** [comment]
Hey man try the new link or go through the apks on the release section of the repo. I have a added multiple apks with diff architectures

https://github.com/ashishkhuraishy/CovidUpdates/releases/tag/v1.0

**Comment by nandgator** [comment]
> Hey man try the new link or go through the apks on the release section of the repo. I have a added multiple apks with diff architectures
> 
> https://github.com/ashishkhuraishy/CovidUpdates/releases/tag/v1.0

Thanks! I tried that out myself (using `--split-per-abi` see the issue: https://github.com/flutter/flutter/issues/58393) it's not working. Even the [docs](https://flutter.dev/docs/deployment/android) say `x86` arch is not supported.

**Comment by ashishkhuraishy** [comment]
> Thanks! I tried that out myself (using `--split-per-abi` see the issue: https://github.com/flutter/flutter/issues/58393) it's not working. Even the [docs](https://flutter.dev/docs/deployment/android) say `x86` arch is not supported.

That is messed up but just found out that only 1% uses `x86` arc. Still wish they fix it on coming updates so that everyone can enjoy using flutter
